### ISSUE TITLE
مشکل با اندروید ۹

### ISSUE THREAD

**Issue by farzin680** [chabokpush/chabok-client-android#22]
متناسفانه اس دی کی چابک با اندروید ۹ کار نمیکند و به نظر سازگار نیست و خطای زیر را در لاگ کت نمایش میدهد

```
2018-12-16 13:50:21.116 5157-5157/fsi.com.a30anat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fsi.com.a30anat, PID: 5157
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry;
        at a.a.<init>(SourceFile:1182)
        at a.a.<init>(SourceFile:119)
        at e.c$c.<init>(SourceFile:348)
        at e.c.connect(SourceFile:92)
        at e.a.<init>(SourceFile:163)
        at e.c.<init>(SourceFile:57)
        at b.i.<init>(SourceFile:24)
        at com.adpdigital.push.AdpPushClient.initializeAdapter(SourceFile:332)
        at com.adpdigital.push.AdpPushClient.<init>(SourceFile:266)
        at com.adpdigital.push.AdpPushClient.init(SourceFile:279)
        at fsi.com.a30anat.SianatApp.initPushClient(SianatApp.java:82)
        at fsi.com.a30anat.SianatApp.onCreate(SianatApp.java:52)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.conn.scheme.SchemeRegistry" on path: DexPathList[[zip file "/data/app/fsi.com.a30anat-cuunX8wPJcrLB05PiQsVEw==/base.apk"],nativeLibraryDirectories=[/data/app/fsi.com.a30anat-cuunX8wPJcrLB05PiQsVEw==/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at a.a.<init>(SourceFile:1182) 
        at a.a.<init>(SourceFile:119) 
        at e.c$c.<init>(SourceFile:348) 
        at e.c.connect(SourceFile:92) 
        at e.a.<init>(SourceFile:163) 
        at e.c.<init>(SourceFile:57) 
        at b.i.<init>(SourceFile:24) 
        at com.adpdigital.push.AdpPushClient.initializeAdapter(SourceFile:332) 
        at com.adpdigital.push.AdpPushClient.<init>(SourceFile:266) 
        at com.adpdigital.push.AdpPushClient.init(SourceFile:279) 
        at fsi.com.a30anat.SianatApp.initPushClient(SianatApp.java:82) 
        at fsi.com.a30anat.SianatApp.onCreate(SianatApp.java:52) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by Husseinhj** [comment]
<p dir="rtl">@farzin680 
کد زیر رو به فایل androidManifest.xml در تگ application اضافه کنید</p>
<pre><code class="language-xml"> &lt;uses-library android:name=&quot;org.apache.http.legacy&quot; android:required=&quot;false&quot; /&gt;</code></pre>

**Comment by Husseinhj** [comment]
<p dir="rtl">در صورت حل نشدن مشکل issue را مجددا باز کنید </p>

**Comment by farzin680** [comment]
> @farzin680 کد زیر رو به فایل androidManifest.xml در تگ application اضافه کنید
> 
> ```
>  <uses-library android:name="org.apache.http.legacy" android:required="false" />
> ```

متشکرم
مشکل حل شد.
