### ISSUE TITLE
عدم توانایی در گرفتن بیلد

### ISSUE THREAD

**Issue by sepehr13494** [chabokpush/chabok-client-android#26]
<p dir="rtl">من این ارور رو دریافت میکنم </p>
<pre><code>E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gugulingo.gugu, PID: 32229
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adpdigital/push/ai;
        at com.adpdigital.push.AdpPushClient.getApplicationInstallReferrer(SourceFile:2346)
        at com.adpdigital.push.AdpPushClient._register(SourceFile:830)
        at com.adpdigital.push.AdpPushClient.register(SourceFile:740)
        at com.adpdigital.push.AdpPushClient.register(SourceFile:727)
        at com.gugulingo.gugu.MainActivity.onCreate(MainActivity.java:75)
        at android.app.Activity.performCreate(Activity.java:6709)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:6267)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.ClassNotFoundException: com.adpdigital.push.ai
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.adpdigital.push.AdpPushClient.getApplicationInstallReferrer(SourceFile:2346) 
        at com.adpdigital.push.AdpPushClient._register(SourceFile:830) 
        at com.adpdigital.push.AdpPushClient.register(SourceFile:740) 
        at com.adpdigital.push.AdpPushClient.register(SourceFile:727) 
        at com.gugulingo.gugu.MainActivity.onCreate(MainActivity.java:75) 
        at android.app.Activity.performCreate(Activity.java:6709) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6267) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/installreferrer/api/InstallReferrerStateListener;
        at com.adpdigital.push.AdpPushClient.getApplicationInstallReferrer(SourceFile:2346) 
        at com.adpdigital.push.AdpPushClient._register(SourceFile:830) 
        at com.adpdigital.push.AdpPushClient.register(SourceFile:740) 
        at com.adpdigital.push.AdpPushClient.register(SourceFile:727) 
        at com.gugulingo.gugu.MainActivity.onCreate(MainActivity.java:75) 
        at android.app.Activity.performCreate(Activity.java:6709) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6267) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.ClassNotFoundException: Didn&#39;t find class &quot;com.android.installreferrer.api.InstallReferrerStateListener&quot; on path: DexPathList[[zip file &quot;/data/app/com.gugulingo.gugu-1/base.apk&quot;],nativeLibraryDirectories=[/data/app/com.gugulingo.gugu-1/lib/arm64, /data/app/com.gugulingo.gugu-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)</code></pre>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<pre><code> Caused by: java.lang.ClassNotFoundException: Didn&#39;t find class &quot;com.android.installreferrer.api.InstallReferrerStateListener&quot;</code></pre></blockquote>
<p dir="rtl"> آیا کتابخونه زیر رو به gradle اضافه کردین؟</p>
<pre><code class="language-groovy">implementation &#39;com.android.installreferrer:installreferrer:1.0&#39;</code></pre>

**Comment by sepehr13494** [comment]
درست شد ولی این نبود قبلا

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">درست شد ولی این نبود قبلا</p>
</blockquote>
<p dir="rtl">لطفا برای بروزرسانی حتما <a href="https://doc.chabokpush.com/android/release-note.html#%D9%86%D8%B3%D8%AE%D9%87-%DB%B2%DB%B1%DB%B5%DB%B0---%DB%B1%DB%B3%DB%B9%DB%B8%DB%B0%DB%B1%DB%B2%DB%B1">لیست تغییرات رو در مستندات مطالعه کنین</a>.</p>
<p dir="rtl"><a href="https://doc.chabokpush.com/android/sdk-setup.html#%D9%85%D8%AF%D9%84-%D9%86%D8%B3%D8%AE%D9%87%DA%AF%D8%B0%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%DA%86%D8%A7%D8%A8%DA%A9-semantic-versioning">همچنین دقت داشته باشین که از کاراکتر wildcard(+) فقط برای نسخه‌های patch استفاده کنید  </a></p>

**Comment by sepehr13494** [comment]
<p dir="rtl">روی دستگاه واقعی درست کار میکنه ولی روی امولاتور ارور زیر دیده میشه:</p>
<pre><code>E/AndroidRuntime: FATAL EXCEPTION: Timer-0
    Process: com.example.sepehr.gugu_helpers, PID: 19013
    java.lang.IllegalArgumentException: Service not registered: com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection@c43431c
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1044)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1337)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
        at com.android.installreferrer.api.InstallReferrerClientImpl.endConnection(InstallReferrerClientImpl.java:170)
        at com.adpdigital.push.ai.a(SourceFile:61)
        at com.adpdigital.push.ai.onInstallReferrerSetupFinished(SourceFile:131)
        at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:162)
        at com.adpdigital.push.ai.startConnection(SourceFile:53)
        at com.adpdigital.push.aj.run(SourceFile:36)
        at java.util.Timer$TimerImpl.run(Timer.java:284)</code></pre>
