### ISSUE TITLE
روی دستگاه واقعی درست کار میکنه ولی روی امولاتور ارور زیر دیده میشه

### ISSUE THREAD

**Issue by Husseinhj** [chabokpush/chabok-client-android#27]
<p dir="rtl">روی دستگاه واقعی درست کار میکنه ولی روی امولاتور ارور زیر دیده میشه:</p>
<pre><code>E/AndroidRuntime: FATAL EXCEPTION: Timer-0
    Process: com.example.sepehr.gugu_helpers, PID: 19013
    java.lang.IllegalArgumentException: Service not registered: com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection@c43431c
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1044)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1337)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
        at com.android.installreferrer.api.InstallReferrerClientImpl.endConnection(InstallReferrerClientImpl.java:170)
        at com.adpdigital.push.ai.a(SourceFile:61)
        at com.adpdigital.push.ai.onInstallReferrerSetupFinished(SourceFile:131)
        at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:162)
        at com.adpdigital.push.ai.startConnection(SourceFile:53)
        at com.adpdigital.push.aj.run(SourceFile:36)
        at java.util.Timer$TimerImpl.run(Timer.java:284)</code></pre>

_Originally posted by @sepehr13494 in https://github.com/chabokpush/chabok-client-android/issues/26#issuecomment-484916643_

**Comment by Husseinhj** [comment]
<p dir="rtl">این مورد در <a href="https://github.com/chabokpush/chabok-client-android/releases/tag/v2.16.0">نسخه ۲.۱۶.۰ </a>حل شده است</p>
